language: node_js
node_js:
- lts/*
notifications:
  slack:
    secure: VJbMnq+tip1hkeVd9CrBwFAPzGiMXkwMdttNOTQUqdEwhiQoAnqt4Lgtj3sKVc6/nee4Qd9puPIr4qqx5Sq7JwwPeAcdUH4qpJKdkA61ST8I2IspA7Y3X0xMSb7prOX+yHjIqhzSbvGuFzeyOK3e4UYLv+H3m/3rF7HrrY3tJhaFyUxiPKHzARzfyaZq/3wvdYpg7mfwr/eu+qCCNDh8L3JWr+9RL5jQJpyaXRiRIXrO3nSVupec7v077yqqgnBT0n6Nw9JVN93uLZ0Fk6848Vyf5h1u9SrVPAneZrUqNsQtl+3agMWh3FQlBQ5Q+CZLyKvNGphSCP9KsY+3qut6r9oO/rQZy4Sm+t1ab6DVY9LpS7WKFDaKmx22IbC8J06WK0TlWiLT7zkuqUpDWHL2V+ljVZDdu51GHuo2Fun2S2PnS9nu+01Rj9VTuTCmhr7FHM0/zxv2FboHnbZYsi6S9Um4PtBZtrIokn52ofK0BfrpEYRZv4FXzPH4OkuFGknlqtyYzeb8skmCf5b2EN8xldvZZtNTfEueQGHvGsqulPKdko9jn/XG6ccV926x0Z7LFFOdX6AOZpNwoTqqnS2uB14nB1naYJDcF0yLLZmMxPaa/RPcmOD8ZjIOLN/I/968ds92+UztVk5mK5JngRebZDWD2/qOFoj7GBk8sLpitRE=
